version: '3.6'
services:
  green-api-app:
    build:
      context: ../
      dockerfile: ./docker/app.Dockerfile
    container_name: green-api-app
    restart: unless-stopped
    env_file:
      - ./app.env
    ports:
      - '3456:8080'
